### PR TITLE
Make category_id() a method on Notification class

### PR DESCRIPTION
**Pull request by michelcrypt4d4mus**
I was still getting wonky results for categories so I fixed up this change I had made on a local branch to make `category_id()` available as a method on `Notification`. Also added a test/fixture for other tests.

set up a separate `test_notification.py` too. if it were my project i would probably break out the `Notification` class to it's own `notification.py` file. makes it a lot easier to find for other people (like me) when classes have their own files.

### CODE REVIEW

**Comment by michelcrypt4d4mus** [comment]
hm, the wonkiness might just be because `pip` failed to update the package after your commits but either way this PR is there if you want it.

**Comment by michelcrypt4d4mus** [comment]
@samschott feel free to close this if it's not a change you're interested in

**Comment by samschott** [comment]
Apologies, I've been a bit behind on reviewing PRs. I'll have another look later this week.

**Comment by samschott** [comment]
Had another look and I'd rather not introduce backend-specific code in the Notification class. If this eventually becomes a significant limitation, I'll consider adding "backend" classes / subclasses for Notifications, but I don't think this is required yet.

**Pull request closed without merging**
